name: Test Workflow

on:
  push:
  pull_request:
  inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  test-work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: start test
        run: echo "Test start"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: good bye
        run: echo "Goodbye"
        shell: bash
    
  
